ignored = ["github.com/hyperledger/Demo/chaincode"]

[[constraint]]
  name = "github.com/hyperledger/fabric-sdk-go"
  revision = "a906355f73d060d7bf95874a9e90dc17589edbb3"

[[override]]
  revision = "4e2dcbde500472449917533851bf4bae9bdff562"
  name = "github.com/cloudflare/cfssl"
